version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: '@types/node'
        versions: ['15', '16']
